baseURL = 'https://lovewifehatetravel.com/'
languageCode = 'en-us'
title = "Love Wife, Hate Travel"
copyright = "© Love Wife, Hate Travel"
disableKinds = ["taxonomy", "term"]
defaultContentLanguage = "en"
enableRobotsTXT = true
theme = "gallery"

# Google Analytics
googleAnalytics = "G-DT7W92NYNR"

[params]
title = ""
description = ""
defaultTheme = "dark"

[author]
name = "LW:HT"

[outputs]
  page = ["HTML"]
  home = ["HTML", "RSS"]
  section = ["HTML"]

[imaging]
  resampleFilter = "CatmullRom"
  quality = 75
  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription"

[module]
  [module.hugoVersion]
    extended = false
    min = "0.112.0"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "hugo_stats.json"
    target = "assets/watching/hugo_stats.json"

[build]
  writeStats = true
  [[build.cachebusters]]
    source = "assets/watching/hugo_stats\\.json"
    target = "styles\\.css"
  [[build.cachebusters]]
    source = "(postcss|tailwind)\\.config\\.js"
    target = "css"
  [[build.cachebusters]]
    source = "assets/.*\\.(js)"
    target = "js"
  [[build.cachebusters]]
    source = "assets/.*\\.(.*)$"
    target = "$1"

[menu]
[[menu.footer]]
  name = "Privacy Policy"
  url = "https://lovewifehatetravel.com/privacy-policy"
  weight = 3
[[menu.footer]]
  name = "Terms of Use"
  url = "https://lovewifehatetravel.com/terms-of-use"
  weight = 3